version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "pip"
    directory: "/app"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
  - package-ecosystem: "pip"
    directory: "/cli"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "npm"
    directory: "ui"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7